s3bucket/apps/accounts/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path

from s3bucket.apps.accounts.views import Login, Logout
from s3bucket.settings.common import STATIC_ROOT, STATIC_URL

app_name = "accounts"

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('password/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
] + static(STATIC_URL, document_root=STATIC_ROOT)

s3bucket/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from s3bucket.settings.common import STATIC_URL, STATIC_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('s3bucket.apps.accounts.urls', namespace='accounts')),
    path('', include("s3bucket.apps.core.urls", namespace="core"))
] + static(STATIC_URL, document_root=STATIC_ROOT)

s3bucket/apps/accounts/models.py
from django.db import models

# Create your models here.

s3bucket/apps/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View


class Login(View):

    template_name = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('core:home'))
        return render(request, self.template_name, {'error': False})

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        if User.objects.filter(username=username):
            username = User.objects.get(username=username).username
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('core:home'))
        else:
            return render(request, self.template_name, {'error': True,
                                                        'message': 'User not authenticated. Wrong login/password'})


class Logout(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))

s3bucket/apps/accounts/templates/login.html
{% extends "adminlte/login.html" %}
{% block title %}Sign In{% endblock %}
{% block logo %}
<div class="login-logo">
    <a href="{% block logo_href %}/{% endblock %}">{% block logo_text %}<b>S3 Bucket</b>{% endblock %}</a>
</div>
{% endblock %}
{% block login_form %}
        <form action="" method="post">
            {% csrf_token %}
            {% if message %}
                <p class="login-box-msg" style="color: red;">{{ message }}</p>
            {% endif %}
            <div class="form-group has-feedback">
                <input name="username" class="form-control" placeholder="Email">
                <span class="glyphicon glyphicon-user form-control-feedback"></span>
            </div>
            <div class="form-group has-feedback">
                <input type="password" name="password" class="form-control" placeholder="Password">
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">
                <div class="col-xs-8">
                </div>

                <div class="col-xs-4">
                    <button type="submit" class="btn btn-primary btn-block btn-flat">Sign in</button>
                </div>
                <div class="clearfix">
                    <div class="separator text-center" >
                        <p class="change_link">Forgot your password?</p>
                         <a href="{% url 'accounts:password_reset' %}" class="to_restore">Restore password</a>
                        <div class="clearfix"></div>&nbsp;</div>
                        <br />
                    </div>
            </div>
        </form>
{% endblock login_form %}